version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    networks:
      - inventory-network
    depends_on:
      - mysql
  mysql:
    container_name: my-sql-database
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory_database
    networks:
      - inventory-network
networks:
  inventory-network:
    driver: bridge
volumes:
  mysql-data: